virginia:
	terraform workspace new virginia || terraform workspace select virginia
	terraform init 
	terraform apply --var-file regions/virginia.tfvars


ohio:
	terraform workspace new ohio || terraform workspace select ohio
	terraform init 
	terraform apply --var-file regions/ohio.tfvars


california:
	terraform workspace new california || terraform workspace select california
	terraform init 
	terraform apply --var-file regions/california.tfvars